// we have to write a basic pipeline script in the Jenkinsfile, which runs 
// node and then sh --node version

pipeline {
    agent {
        docker {
            image 'node:14'
            args '-u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
            }
        }
    }
}